# Generated by Django 5.0.1 on 2024-03-18 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0002_movie_available'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
