# Generated by Django 5.0.1 on 2024-03-19 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0007_remove_movie_categories_movie_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['title'], 'verbose_name': 'Movie', 'verbose_name_plural': 'Moves'},
        ),
    ]
